version: "3.4"
services:
  videos-web:
    container_name: videos-web
    image: aimvector/service-mesh:videos-web-2.0.5
    build:
      context: ./applications/videos-web
    ports:
      - 80:80
  playlists-api:
    container_name: playlists-api
    image: aimvector/service-mesh:playlists-api-2.0.5
    build:
      context: ./applications/playlists-api
    environment:
    - "JAEGER_REPORTER_LOG_SPANS=true"
    - "ENVIRONMENT=DEBUG"
    - "REDIS_HOST=playlists-db"
    - "REDIS_PORT=6379"
    - "JAEGER_HOST_PORT=jaeger:6831"
    ports:
    - 81:10010
  videos-api:
    container_name: videos-api
    image: aimvector/service-mesh:videos-api-2.0.5
    build:
      context: ./applications/videos-api
    environment:
    - "JAEGER_REPORTER_LOG_SPANS=true"
    - "ENVIRONMENT=DEBUG"
    - "REDIS_HOST=videos-db"
    - "REDIS_PORT=6379"
    - "JAEGER_HOST_PORT=jaeger:6831"
    ports:
    - 82:10010
  videos-db:
    container_name: videos-db
    image: redis:6.0-alpine
    command: [ "redis-server" , "--dir", "/tmp", "--appendonly", "yes"]
    volumes:
      - ./applications/videos-db/appendonly.aof:/tmp/appendonly.aof
  playlists-db:
    container_name: playlists-db
    image: redis:6.0-alpine
    command: [ "redis-server" , "--dir", "/tmp", "--appendonly", "yes"]
    volumes:
      - ./applications/playlists-db/appendonly.aof:/tmp/appendonly.aof
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
    - 16686:16686
    - 14269:14269